services:
  painel-esus-sync:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - esus_sync_data:/app/data
    ports:
      - "3000:3000"

volumes:
  esus_sync_data:
